version: '3'

services:
 app:
  build:
   context: .
   dockerfile: Dockerfile
   args:
    VARIANT: 'focal'

  volumes:
   - ..:/workspace:cached
  command: sleep infinity
  network_mode: service:db

 db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: 'dfjkandfvlakfjsvn'
   MYSQL_DATABASE: 'construct'
   MYSQL_USER: 'admin'
   MYSQL_PASSWORD: 'ksmevlsdfkvsdfv'
